FROM python:3.12-alpine@sha256:c7eb5c92b7933fe52f224a91a1ced27b91840ac9c69c58bef40d602156bcdb41

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="git-batch"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/git-batch"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/git-batch"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/git-batch"

ENV PY_COLORS=1
ENV TZ=UTC

ADD dist/git_batch-*.whl /

RUN apk --update add --virtual .build-deps build-base libffi-dev openssl-dev && \
    apk --update add git && \
    pip install --upgrade --no-cache-dir pip && \
    pip install --no-cache-dir $(find / -name "git_batch-*.whl") && \
    apk del .build-deps && \
    rm -f git_batch-*.whl && \
    rm -rf /var/cache/apk/* && \
    rm -rf /root/.cache/

USER root
CMD []
ENTRYPOINT ["/usr/local/bin/git-batch"]
