FROM arm32v7/python:3.10-alpine@sha256:f0031267e811a6c3cc6997863e7b90842bca11b6de35c3ad6ef8a264d6a01a2c

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="git-batch"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/git-batch"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/git-batch"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/git-batch"

ENV PY_COLORS=1
ENV TZ=UTC

ADD dist/git_batch-*.whl /

RUN apk --update add --virtual .build-deps build-base libffi-dev openssl-dev && \
    apk --update add git && \
    pip install --upgrade --no-cache-dir pip && \
    pip install --no-cache-dir $(find / -name "git_batch-*.whl") && \
    apk del .build-deps && \
    rm -f git_batch-*.whl && \
    rm -rf /var/cache/apk/* && \
    rm -rf /root/.cache/

USER root
CMD []
ENTRYPOINT ["/usr/local/bin/git-batch"]
