---
when:
  - event: [pull_request, tag]
  - event: [push, manual]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

matrix:
  PYTHON_VERSION:
    - "3.10"
    - "3.11"

steps:
  fetch:
    image: docker.io/library/python:3.11
    commands:
      - git fetch -tq

  pytest:
    image: docker.io/library/python:${PYTHON_VERSION}
    commands:
      - pip install poetry poetry-dynamic-versioning -qq
      - poetry install
      - poetry version
      - poetry run git-batch --help
    environment:
      PY_COLORS: "1"
